pipelines:
  my-constituency:
    group: common
    label_template: "${COUNT}"
    materials:
      my-constituency-git:
        git: https://github.com/ukparliament/my-constituency-app.git
        branch: development
        auto_update: true
    stages:
      - deploy:
          jobs:
            deploy:
              tasks:
                - exec:
                    run_if: passed
                    command: make
                    arguments:
                      - deploy_to_release

environments:
  Web.DEVCI:
    pipelines:
      - my-constituency