pipelines:
  my-constituency:
    group: Static-Websites
    label_template: "${COUNT}"
    materials:
      my-constituency-git:
        git: https://github.com/ukparliament/my-constituency-app.git
        branch: master
        auto_update: true
    stages:
      - deploy:
          approval: manual
          jobs:
            deploy:
              tasks:
                - exec:
                    run_if: passed
                    command: make
                    arguments:
                      - deploy_to_release


environments:
  Web.LIVE:
    pipelines:
      - my-constituency